// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import auth "github.com/taeho-io/family/idl/generated/go/pb/family/auth"

import config "github.com/taeho-io/family/services/base/config"
import context "context"
import grpc "google.golang.org/grpc"
import logrus "github.com/sirupsen/logrus"
import mock "github.com/stretchr/testify/mock"
import token "github.com/taeho-io/family/services/auth/token"

// IFace is an autogenerated mock type for the IFace type
type IFace struct {
	mock.Mock
}

// Auth provides a mock function with given fields: _a0, _a1
func (_m *IFace) Auth(_a0 context.Context, _a1 *auth.AuthRequest) (*auth.AuthResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *auth.AuthResponse
	if rf, ok := ret.Get(0).(func(context.Context, *auth.AuthRequest) *auth.AuthResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AuthResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *auth.AuthRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Config provides a mock function with given fields:
func (_m *IFace) Config() config.IFace {
	ret := _m.Called()

	var r0 config.IFace
	if rf, ok := ret.Get(0).(func() config.IFace); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.IFace)
		}
	}

	return r0
}

// GetAccountIDFromContext provides a mock function with given fields: ctx
func (_m *IFace) GetAccountIDFromContext(ctx context.Context) string {
	ret := _m.Called(ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// HasPermissionByAccountID provides a mock function with given fields: ctx, accountID
func (_m *IFace) HasPermissionByAccountID(ctx context.Context, accountID string) error {
	ret := _m.Called(ctx, accountID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Logger provides a mock function with given fields:
func (_m *IFace) Logger() *logrus.Entry {
	ret := _m.Called()

	var r0 *logrus.Entry
	if rf, ok := ret.Get(0).(func() *logrus.Entry); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*logrus.Entry)
		}
	}

	return r0
}

// Parse provides a mock function with given fields: _a0, _a1
func (_m *IFace) Parse(_a0 context.Context, _a1 *auth.ParseRequest) (*auth.ParseResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *auth.ParseResponse
	if rf, ok := ret.Get(0).(func(context.Context, *auth.ParseRequest) *auth.ParseResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.ParseResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *auth.ParseRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Refresh provides a mock function with given fields: _a0, _a1
func (_m *IFace) Refresh(_a0 context.Context, _a1 *auth.RefreshRequest) (*auth.RefreshResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *auth.RefreshResponse
	if rf, ok := ret.Get(0).(func(context.Context, *auth.RefreshRequest) *auth.RefreshResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RefreshResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *auth.RefreshRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterService provides a mock function with given fields: _a0
func (_m *IFace) RegisterService(_a0 *grpc.Server) {
	_m.Called(_a0)
}

// Token provides a mock function with given fields:
func (_m *IFace) Token() token.IFace {
	ret := _m.Called()

	var r0 token.IFace
	if rf, ok := ret.Get(0).(func() token.IFace); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(token.IFace)
		}
	}

	return r0
}

// Validate provides a mock function with given fields: _a0, _a1
func (_m *IFace) Validate(_a0 context.Context, _a1 *auth.ValidateRequest) (*auth.ValidateResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *auth.ValidateResponse
	if rf, ok := ret.Get(0).(func(context.Context, *auth.ValidateRequest) *auth.ValidateResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.ValidateResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *auth.ValidateRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
